<?php

namespace Ankitpise\RouteBinder;

use Illuminate\Support\ServiceProvider;

class RouteBinderServiceProvider extends ServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(){
        $this->app->configure('modelbinder');
    }

}